name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Set up Clojure
        uses: DeLaGuardo/setup-clojure@10.2
        with:
          cli: 1.11.1.1413

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install npm deps
        run: npm install

      - name: Build release with shadow-cljs
        run: npx shadow-cljs release release

      - name: Commit docs folder
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/*
          git commit -m "Update GitHub Pages build" || echo "No changes to commit"
          git push
