name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # needed to push to gh-pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
	  java-version: 21

      - name: Set up Clojure
        uses: DeLaGuardo/setup-clojure@10.2
        with:
          cli: 1.11.1.1413

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build CSS with Tailwind
        run: npm run build:css

      - name: Build ClojureScript with shadow-cljs
        run: npx shadow-cljs release app

      - name: Prepare deploy folder
        run: |
          mkdir -p out
          cp -r public/* out/
          cp -r target/public/* out/
	  cp -r public/* docs/
	  cp -r target/public/* docs/
	  

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
